### ISSUE TITLE
Implementing car-auction locally instead of IBM cloud

### ISSUE THREAD

**Issue by nimaafraz** [IBM/car-auction-network-fabric-node-sdk#4]
What changes should I make to be able to deploy the car auction network locally?

**Comment by varunagarwal315** [comment]
A quick way to do this is to clone https://github.com/hyperledger/fabric-samples , then dump the chaincode inside the chaincode folder and follow the setup used over there. Don't forget to change links and ports for connections for the CA. For example [this](https://github.com/IBM/car-auction-network-fabric-node-sdk/blob/master/enrollAdmin.js#L43) would need editing to be [this](https://github.com/hyperledger/fabric-samples/blob/release-1.4/fabcar/javascript-low-level/enrollAdmin.js#L42).

You would need to add a `./startFabric.sh` script [like so ](https://github.com/hyperledger/fabric-samples/blob/release-1.4/fabcar/startFabric.sh). 

I am in the process of doing this, can share some more info once I am done my testing and deployment

**Comment by horeaporutiu** [comment]
@nimaafraz I recommend using the VSCode extension - this will deploy a local Hyperledger Fabric network on your computer. In my personal opinion, it's easier to work with than through the CLI's.

It may take a bit of getting used to - but after you get the hang of it it will speed up development time considerably. 

You can just follow this tutorial - https://developer.ibm.com/tutorials/ibm-blockchain-platform-vscode-smart-contract/ And then just change the chaincode just a bit - add in the functions from this repo in the smart contract folder, and you should be good to go.

Another great tutorial for using VSCode extensions for deploying contracts locally is this one - https://github.com/IBM/global-financing-blockchain

Note that you can do what @varunagarwal315 said as well - I am just giving an alternative approach. Hope this helps.
